POST http://localhost:8000/api/webhook/sepay
Content-Type: application/json
Authorization:Apikey TFAW4EUWJ4DTHSMPN65ZFRZYICZE7DGPQASJV5CBTG7RY12CNN30HQMKW3SXRBE1

{
  "id": 92704,
  "gateway": "Vietcombank",
  "transactionDate": "2023-03-25 14:02:37",
  "accountNumber": "0123499999",
  "code": null,
  "content": "STUDENTTB_FA25_IW_68bf106227260",
  "transferType": "in",
  "transferAmount": 1500000,
  "accumulated": 19077000,
  "subAccount": null,
  "referenceCode": "MBVCB.3278907687",
  "description": ""
}
